apiVersion: k0sctl.k0sproject.io/v1beta1

kind: Cluster

metadata:
  name: k0s-cluster

spec:
  hosts:
  - ssh:
      address: 192.168.0.50
      user: vagrant
      port: 22
      keyPath: /Users/mihado/.ssh/id_rsa
    role: controller

  - ssh:
      address: 192.168.0.60
      user: vagrant
      port: 22
      keyPath: /Users/mihado/.ssh/id_rsa
    role: worker
  - ssh:
      address: 192.168.0.61
      user: vagrant
      port: 22
      keyPath: /Users/mihado/.ssh/id_rsa
    role: worker
  - ssh:
      address: 192.168.0.62
      user: vagrant
      port: 22
      keyPath: /Users/mihado/.ssh/id_rsa
    role: worker

  k0s:
    version: 1.23.7+k0s.0
    dynamicConfig: false
